#!/usr/bin/env python3
"""Copy the PythonOS runtime into a folder so a platform build can package it.

Every platform build (Linux, Windows, Android, ISO) starts from this, so the list of
files that make up the OS lives in exactly one place.

    python OS_Export/stage.py <dest> [--vendor pkg ...]
    python OS_Export/stage.py --print-version

--vendor pip-installs the named (pure Python) packages into <dest>/site-packages,
for builds that cannot run pip at runtime. main.py adds that folder to sys.path.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))

PAYLOAD_FILES = [
    "main.py", "shell.py", "users.py", "config.json",
    "requirements.txt", "boot-requirements.txt", "readme.md",
]
PAYLOAD_DIRS = ["commands", "core", "programs", "pyos"]
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo")
FORBIDDEN_TOP = {"online_packages", "files", "OS_Export", "tools", ".github", ".OSData", "users.json", "current_user.json"}


def version():
    """VERSION env var (a tag like v1.2.0 is fine) or the version in config.json."""
    env = os.environ.get("VERSION", "").strip()
    if env and env != "dev":
        return env.lstrip("v")
    try:
        with open(os.path.join(REPO, "config.json"), encoding="utf-8") as f:
            base = str(json.load(f).get("version", "1.0"))
    except (OSError, ValueError):
        base = "1.0"
    return base if not env else f"{base}-dev"


EXPORTS_FILE = os.path.join(REPO, "OS_Export", "exports.json")
PLATFORMS = ("android", "windows", "linux", "iso")


def exports():
    """OS_Export/exports.json: for each export, its api, assets and the inputs that decide whether it is rebuilt."""
    with open(EXPORTS_FILE, encoding="utf-8") as f:
        data = json.load(f)
    return {k: v for k, v in data.items() if not k.startswith("_")}


def export_info(platform):
    # An export's version is the release it was built in. Unchanged exports are not rebuilt (see plan.py),
    # so theirs stays at the release where they last changed.
    entry = exports()[platform]
    return {"platform": platform, "version": version(), "api": entry["api"]}


def write_export(platform, path):
    """Write an export's identity: JSON, or a Python module (pyos_export.py) when path ends in .py."""
    info = export_info(platform)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        if path.endswith(".py"):
            f.write("# Generated by OS_Export/stage.py - which export this is (see pyos/export.py)\n")
            f.write(f"INFO = {info!r}\n")
        else:
            json.dump(info, f, indent=2)
            f.write("\n")


def stage(dest, vendor=(), export=None):
    dest = os.path.abspath(dest)
    if os.path.exists(dest):
        shutil.rmtree(dest)
    os.makedirs(dest)
    for name in PAYLOAD_FILES:
        src = os.path.join(REPO, name)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(dest, name))
    for name in PAYLOAD_DIRS:
        shutil.copytree(os.path.join(REPO, name), os.path.join(dest, name), ignore=IGNORE)
    # Marketplace packages, user data and build tooling must never ship inside the OS itself
    # (packages are downloaded from the marketplace and live in files/installed_*).
    for dirpath, dirnames, filenames in os.walk(dest):
        for name in dirnames + filenames:
            rel = os.path.relpath(os.path.join(dirpath, name), dest).replace(os.sep, "/")
            if rel.split("/")[0] in FORBIDDEN_TOP or "installed_" in name:
                raise SystemExit(f"stage.py: '{rel}' must not be part of the OS payload")
    with open(os.path.join(dest, "VERSION"), "w", encoding="utf-8", newline="\n") as f:
        f.write(version() + "\n")
    if export:
        write_export(export, os.path.join(dest, "export.json"))
    if vendor:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "--no-compile",
                               "--target", os.path.join(dest, "site-packages"), *vendor])
    return dest


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("dest", nargs="?", help="folder to create (replaced if it exists)")
    parser.add_argument("--vendor", nargs="*", default=[], metavar="PKG", help="pure-Python packages to bundle")
    parser.add_argument("--print-version", action="store_true", help="print the version and exit")
    parser.add_argument("--export", choices=PLATFORMS, help="also write export.json for this platform into dest")
    parser.add_argument("--write-export", nargs=2, metavar=("PLATFORM", "PATH"),
                        help="only write an export identity file (.json or .py) and exit")
    args = parser.parse_args()
    if args.print_version:
        print(version())
        return
    if args.write_export:
        platform, path = args.write_export
        if platform not in PLATFORMS:
            parser.error(f"platform must be one of {', '.join(PLATFORMS)}")
        write_export(platform, path)
        return
    if not args.dest:
        parser.error("dest is required")
    print(f"Staged PythonOS {version()} in {stage(args.dest, args.vendor, args.export)}")


if __name__ == "__main__":
    main()
