package com.pythonos.installer

import android.content.Context
import java.util.Locale

/**
 * The installer's language. It starts as the phone's language when we have it (Spanish, French, German), and the chips on the
 * screen change it, the way the Windows installer's language row does. Texts are looked up by their English wording; anything
 * without a translation shows in English. {0}, {1} ... in a text are filled in from the arguments.
 */
object Lang {
    val choices = listOf("en" to "English", "es" to "Español", "fr" to "Français", "de" to "Deutsch")
    var code = "en"
        private set

    fun init(context: Context) {
        val saved = try { context.getSharedPreferences("installer", Context.MODE_PRIVATE).getString("lang", null) } catch (e: Exception) { null }
        val wanted = saved ?: Locale.getDefault().language
        code = if (choices.any { it.first == wanted }) wanted else "en"
    }

    fun choose(context: Context, wanted: String) {
        code = wanted
        try { context.getSharedPreferences("installer", Context.MODE_PRIVATE).edit().putString("lang", wanted).apply() } catch (e: Exception) { }
    }

    fun text(english: String, args: Array<out Any?>): String {
        var out = (when (code) { "es" -> ES; "fr" -> FR; "de" -> DE; else -> null })?.get(english) ?: english
        for ((i, value) in args.withIndex()) out = out.replace("{$i}", value?.toString() ?: "")
        return out
    }

    private val ES = mapOf(
        "Install and update the app" to "Instala y actualiza la aplicación",
        "Language" to "Idioma",
        "Check" to "Comprobar",
        "Install" to "Instalar",
        "Done" to "Listo",
        "Check this device" to "Comprobar este dispositivo",
        "Find the version" to "Buscar la versión",
        "Download" to "Descargar",
        "Check the download" to "Comprobar la descarga",
        "Open PythonOS" to "Abrir PythonOS",
        "What is new" to "Novedades",
        "Other versions" to "Otras versiones",
        "Uninstall" to "Desinstalar",
        "Copy details" to "Copiar detalles",
        "Check again" to "Comprobar de nuevo",
        "Try again" to "Reintentar",
        "Device" to "Dispositivo",
        "Installed" to "Instalada",
        "Latest" to "Última",
        "32-bit processor" to "procesador de 32 bits",
        "Downloads come from github.com/Kalmai221/PythonOS and are checked against the release's SHA-256 checksums before Android is asked to install them. The file is kept until it is installed." to "Las descargas vienen de github.com/Kalmai221/PythonOS y se comprueban con las sumas SHA-256 de la versión antes de pedir a Android que las instale. El archivo se conserva hasta que se instala.",
        "✓  PythonOS {0} was installed successfully" to "✓  PythonOS {0} se instaló correctamente",
        "It is ready to use. Open it now, or find PythonOS in your app list. Type help inside it to get started, and updatecheck to update it later. The downloaded file has been removed to free the space." to "Está listo para usar. Ábrelo ahora o busca PythonOS en tu lista de aplicaciones. Escribe help dentro para empezar y updatecheck para actualizarlo más tarde. El archivo descargado se ha borrado para liberar espacio.",
        "Not available on this device" to "No disponible en este dispositivo",
        "This device has a 32-bit processor, which the PythonOS app does not support yet." to "Este dispositivo tiene un procesador de 32 bits, que la aplicación PythonOS aún no admite.",
        "PythonOS is not installed" to "PythonOS no está instalado",
        "PythonOS {0} is installed" to "PythonOS {0} está instalado",
        "Looking for the latest version..." to "Buscando la última versión...",
        "The latest version is {0} (released {1}{2})." to "La última versión es {0} (publicada {1}{2}).",
        "Install PythonOS {0}" to "Instalar PythonOS {0}",
        "An update is available" to "Hay una actualización",
        "You have the app {0}. The latest app is {1} (released {2}{3}). PythonOS also updates itself from inside with updatecheck." to "Tienes la aplicación {0}. La última es {1} (publicada {2}{3}). PythonOS también se actualiza desde dentro con updatecheck.",
        "Update the app to {0}" to "Actualizar la aplicación a {0}",
        "The app is up to date" to "La aplicación está al día",
        "You have the latest app ({0}). The newest release, {1}, only changed PythonOS itself, and that updates from inside: open PythonOS and type updatecheck. There is nothing to install here." to "Tienes la última aplicación ({0}). La versión más reciente, {1}, solo cambió PythonOS en sí, y eso se actualiza desde dentro: abre PythonOS y escribe updatecheck. Aquí no hay nada que instalar.",
        "You have the latest version, {0}." to "Tienes la última versión, {0}.",
        "You have {0}, which is newer than the latest release's app ({1})." to "Tienes {0}, que es más nueva que la aplicación de la última versión ({1}).",
        "Could not check for the latest version: {0}" to "No se pudo buscar la última versión: {0}",
        "Allow installing apps" to "Permitir instalar aplicaciones",
        "Android needs your permission before this app can install PythonOS. On the next screen, switch on \"Allow from this source\", then come back here." to "Android necesita tu permiso para que esta aplicación pueda instalar PythonOS. En la siguiente pantalla, activa \"Permitir desde esta fuente\" y vuelve aquí.",
        "Open settings" to "Abrir ajustes",
        "Not now" to "Ahora no",
        "Use mobile data?" to "¿Usar datos móviles?",
        "This download is {0} and you are not on an unlimited connection. Download it now?" to "Esta descarga es de {0} y no tienes una conexión ilimitada. ¿Descargarla ahora?",
        "Wait for Wi-Fi" to "Esperar al Wi-Fi",
        "Installing {0}" to "Instalando {0}",
        "Keep this screen open until Android asks you to confirm." to "Mantén esta pantalla abierta hasta que Android te pida confirmar.",
        "{0} of {1}" to "{0} de {1}",
        "%d s left" to "faltan %d s",
        "Downloaded and checked (SHA-256 {0}...). Confirm the installation in the window Android shows." to "Descargado y comprobado (SHA-256 {0}...). Confirma la instalación en la ventana que muestra Android.",
        "Not installed: {0}" to "No instalado: {0}",
        "That did not work" to "No ha funcionado",
        "The downloaded file has been removed." to "El archivo descargado se ha borrado.",
        "PythonOS is not installed." to "PythonOS no está instalado.",
        "PythonOS is installed." to "PythonOS está instalado.",
        "The downloaded file is kept, so trying again does not download it again." to "El archivo descargado se conserva, así que reintentar no lo descarga de nuevo.",
        "No release notes." to "Sin notas de la versión.",
        "What is new in {0}" to "Novedades de {0}",
        "Tap to open the full release page." to "Toca para abrir la página completa de la versión.",
        "Looking up versions..." to "Buscando versiones...",
        "No versions found." to "No se encontraron versiones.",
        "Could not list versions: {0}" to "No se pudieron listar las versiones: {0}",
        "Install a version" to "Instalar una versión",
        "Cancel" to "Cancelar",
        "Install an older version?" to "¿Instalar una versión anterior?",
        "You have {0}. Android refuses to install an older version over a newer one. If it does, uninstall PythonOS first (back up your files with the backup command inside PythonOS), then install again." to "Tienes {0}. Android se niega a instalar una versión anterior sobre una más nueva. Si lo hace, desinstala PythonOS primero (haz una copia de tus archivos con el comando backup dentro de PythonOS) y vuelve a instalar.",
        "Try anyway" to "Intentar igualmente",
        "Uninstall PythonOS?" to "¿Desinstalar PythonOS?",
        "This removes PythonOS and everything stored inside it (accounts, files, settings) from this device. Back up first with the backup command inside PythonOS." to "Esto elimina PythonOS y todo lo que guarda (cuentas, archivos, ajustes) de este dispositivo. Haz antes una copia con el comando backup dentro de PythonOS.",
        "Details copied. Paste them into a bug report." to "Detalles copiados. Pégalos en un informe de error.",
    )

    private val FR = mapOf(
        "Install and update the app" to "Installer et mettre à jour l'application",
        "Language" to "Langue",
        "Check" to "Vérifier",
        "Install" to "Installer",
        "Done" to "Terminé",
        "Check this device" to "Vérifier cet appareil",
        "Find the version" to "Trouver la version",
        "Download" to "Télécharger",
        "Check the download" to "Vérifier le téléchargement",
        "Open PythonOS" to "Ouvrir PythonOS",
        "What is new" to "Nouveautés",
        "Other versions" to "Autres versions",
        "Uninstall" to "Désinstaller",
        "Copy details" to "Copier les détails",
        "Check again" to "Vérifier à nouveau",
        "Try again" to "Réessayer",
        "Device" to "Appareil",
        "Installed" to "Installée",
        "Latest" to "Dernière",
        "32-bit processor" to "processeur 32 bits",
        "Downloads come from github.com/Kalmai221/PythonOS and are checked against the release's SHA-256 checksums before Android is asked to install them. The file is kept until it is installed." to "Les téléchargements viennent de github.com/Kalmai221/PythonOS et sont vérifiés avec les sommes SHA-256 de la version avant de demander à Android de les installer. Le fichier est conservé jusqu'à son installation.",
        "✓  PythonOS {0} was installed successfully" to "✓  PythonOS {0} a été installé avec succès",
        "It is ready to use. Open it now, or find PythonOS in your app list. Type help inside it to get started, and updatecheck to update it later. The downloaded file has been removed to free the space." to "Il est prêt à l'emploi. Ouvrez-le maintenant ou trouvez PythonOS dans votre liste d'applications. Tapez help à l'intérieur pour commencer, et updatecheck pour le mettre à jour plus tard. Le fichier téléchargé a été supprimé pour libérer de la place.",
        "Not available on this device" to "Indisponible sur cet appareil",
        "This device has a 32-bit processor, which the PythonOS app does not support yet." to "Cet appareil a un processeur 32 bits, que l'application PythonOS ne prend pas encore en charge.",
        "PythonOS is not installed" to "PythonOS n'est pas installé",
        "PythonOS {0} is installed" to "PythonOS {0} est installé",
        "Looking for the latest version..." to "Recherche de la dernière version...",
        "The latest version is {0} (released {1}{2})." to "La dernière version est la {0} (publiée {1}{2}).",
        "Install PythonOS {0}" to "Installer PythonOS {0}",
        "An update is available" to "Une mise à jour est disponible",
        "You have the app {0}. The latest app is {1} (released {2}{3}). PythonOS also updates itself from inside with updatecheck." to "Vous avez l'application {0}. La dernière est la {1} (publiée {2}{3}). PythonOS se met aussi à jour de l'intérieur avec updatecheck.",
        "Update the app to {0}" to "Mettre l'application à jour vers {0}",
        "The app is up to date" to "L'application est à jour",
        "You have the latest app ({0}). The newest release, {1}, only changed PythonOS itself, and that updates from inside: open PythonOS and type updatecheck. There is nothing to install here." to "Vous avez la dernière application ({0}). La version la plus récente, {1}, n'a changé que PythonOS lui-même, qui se met à jour de l'intérieur : ouvrez PythonOS et tapez updatecheck. Il n'y a rien à installer ici.",
        "You have the latest version, {0}." to "Vous avez la dernière version, {0}.",
        "You have {0}, which is newer than the latest release's app ({1})." to "Vous avez la {0}, plus récente que l'application de la dernière version ({1}).",
        "Could not check for the latest version: {0}" to "Impossible de chercher la dernière version : {0}",
        "Allow installing apps" to "Autoriser l'installation d'applications",
        "Android needs your permission before this app can install PythonOS. On the next screen, switch on \"Allow from this source\", then come back here." to "Android a besoin de votre accord pour que cette application puisse installer PythonOS. Sur l'écran suivant, activez \"Autoriser depuis cette source\", puis revenez ici.",
        "Open settings" to "Ouvrir les réglages",
        "Not now" to "Pas maintenant",
        "Use mobile data?" to "Utiliser les données mobiles ?",
        "This download is {0} and you are not on an unlimited connection. Download it now?" to "Ce téléchargement fait {0} et votre connexion n'est pas illimitée. Le télécharger maintenant ?",
        "Wait for Wi-Fi" to "Attendre le Wi-Fi",
        "Installing {0}" to "Installation de {0}",
        "Keep this screen open until Android asks you to confirm." to "Gardez cet écran ouvert jusqu'à ce qu'Android vous demande de confirmer.",
        "{0} of {1}" to "{0} sur {1}",
        "%d s left" to "%d s restantes",
        "Downloaded and checked (SHA-256 {0}...). Confirm the installation in the window Android shows." to "Téléchargé et vérifié (SHA-256 {0}...). Confirmez l'installation dans la fenêtre qu'affiche Android.",
        "Not installed: {0}" to "Non installé : {0}",
        "That did not work" to "Cela n'a pas fonctionné",
        "The downloaded file has been removed." to "Le fichier téléchargé a été supprimé.",
        "PythonOS is not installed." to "PythonOS n'est pas installé.",
        "PythonOS is installed." to "PythonOS est installé.",
        "The downloaded file is kept, so trying again does not download it again." to "Le fichier téléchargé est conservé, donc réessayer ne le télécharge pas de nouveau.",
        "No release notes." to "Pas de notes de version.",
        "What is new in {0}" to "Nouveautés de {0}",
        "Tap to open the full release page." to "Touchez pour ouvrir la page complète de la version.",
        "Looking up versions..." to "Recherche des versions...",
        "No versions found." to "Aucune version trouvée.",
        "Could not list versions: {0}" to "Impossible de lister les versions : {0}",
        "Install a version" to "Installer une version",
        "Cancel" to "Annuler",
        "Install an older version?" to "Installer une version plus ancienne ?",
        "You have {0}. Android refuses to install an older version over a newer one. If it does, uninstall PythonOS first (back up your files with the backup command inside PythonOS), then install again." to "Vous avez la {0}. Android refuse d'installer une version plus ancienne par-dessus une plus récente. Dans ce cas, désinstallez d'abord PythonOS (sauvegardez vos fichiers avec la commande backup dans PythonOS), puis réinstallez.",
        "Try anyway" to "Essayer quand même",
        "Uninstall PythonOS?" to "Désinstaller PythonOS ?",
        "This removes PythonOS and everything stored inside it (accounts, files, settings) from this device. Back up first with the backup command inside PythonOS." to "Cela supprime PythonOS et tout ce qu'il contient (comptes, fichiers, réglages) de cet appareil. Sauvegardez d'abord avec la commande backup dans PythonOS.",
        "Details copied. Paste them into a bug report." to "Détails copiés. Collez-les dans un rapport de bogue.",
    )

    private val DE = mapOf(
        "Install and update the app" to "Die App installieren und aktualisieren",
        "Language" to "Sprache",
        "Check" to "Prüfen",
        "Install" to "Installieren",
        "Done" to "Fertig",
        "Check this device" to "Dieses Gerät prüfen",
        "Find the version" to "Version suchen",
        "Download" to "Herunterladen",
        "Check the download" to "Download prüfen",
        "Open PythonOS" to "PythonOS öffnen",
        "What is new" to "Neuigkeiten",
        "Other versions" to "Andere Versionen",
        "Uninstall" to "Deinstallieren",
        "Copy details" to "Details kopieren",
        "Check again" to "Erneut prüfen",
        "Try again" to "Erneut versuchen",
        "Device" to "Gerät",
        "Installed" to "Installiert",
        "Latest" to "Neueste",
        "32-bit processor" to "32-Bit-Prozessor",
        "Downloads come from github.com/Kalmai221/PythonOS and are checked against the release's SHA-256 checksums before Android is asked to install them. The file is kept until it is installed." to "Downloads stammen von github.com/Kalmai221/PythonOS und werden mit den SHA-256-Prüfsummen der Version geprüft, bevor Android sie installieren soll. Die Datei bleibt erhalten, bis sie installiert ist.",
        "✓  PythonOS {0} was installed successfully" to "✓  PythonOS {0} wurde erfolgreich installiert",
        "It is ready to use. Open it now, or find PythonOS in your app list. Type help inside it to get started, and updatecheck to update it later. The downloaded file has been removed to free the space." to "Es ist einsatzbereit. Öffnen Sie es jetzt oder finden Sie PythonOS in Ihrer App-Liste. Geben Sie darin help ein, um zu beginnen, und später updatecheck zum Aktualisieren. Die heruntergeladene Datei wurde entfernt, um Platz freizugeben.",
        "Not available on this device" to "Auf diesem Gerät nicht verfügbar",
        "This device has a 32-bit processor, which the PythonOS app does not support yet." to "Dieses Gerät hat einen 32-Bit-Prozessor, den die PythonOS-App noch nicht unterstützt.",
        "PythonOS is not installed" to "PythonOS ist nicht installiert",
        "PythonOS {0} is installed" to "PythonOS {0} ist installiert",
        "Looking for the latest version..." to "Suche nach der neuesten Version...",
        "The latest version is {0} (released {1}{2})." to "Die neueste Version ist {0} (veröffentlicht {1}{2}).",
        "Install PythonOS {0}" to "PythonOS {0} installieren",
        "An update is available" to "Ein Update ist verfügbar",
        "You have the app {0}. The latest app is {1} (released {2}{3}). PythonOS also updates itself from inside with updatecheck." to "Sie haben die App {0}. Die neueste App ist {1} (veröffentlicht {2}{3}). PythonOS aktualisiert sich auch von innen mit updatecheck.",
        "Update the app to {0}" to "App auf {0} aktualisieren",
        "The app is up to date" to "Die App ist aktuell",
        "You have the latest app ({0}). The newest release, {1}, only changed PythonOS itself, and that updates from inside: open PythonOS and type updatecheck. There is nothing to install here." to "Sie haben die neueste App ({0}). Die neueste Version, {1}, hat nur PythonOS selbst geändert, und das aktualisiert sich von innen: Öffnen Sie PythonOS und geben Sie updatecheck ein. Hier gibt es nichts zu installieren.",
        "You have the latest version, {0}." to "Sie haben die neueste Version, {0}.",
        "You have {0}, which is newer than the latest release's app ({1})." to "Sie haben {0}, das neuer ist als die App der neuesten Version ({1}).",
        "Could not check for the latest version: {0}" to "Die neueste Version konnte nicht gesucht werden: {0}",
        "Allow installing apps" to "Installieren von Apps erlauben",
        "Android needs your permission before this app can install PythonOS. On the next screen, switch on \"Allow from this source\", then come back here." to "Android braucht Ihre Erlaubnis, damit diese App PythonOS installieren kann. Schalten Sie auf dem nächsten Bildschirm \"Von dieser Quelle zulassen\" ein und kehren Sie dann hierher zurück.",
        "Open settings" to "Einstellungen öffnen",
        "Not now" to "Nicht jetzt",
        "Use mobile data?" to "Mobile Daten verwenden?",
        "This download is {0} and you are not on an unlimited connection. Download it now?" to "Dieser Download ist {0} groß und Ihre Verbindung ist nicht unbegrenzt. Jetzt herunterladen?",
        "Wait for Wi-Fi" to "Auf WLAN warten",
        "Installing {0}" to "{0} wird installiert",
        "Keep this screen open until Android asks you to confirm." to "Lassen Sie diesen Bildschirm offen, bis Android Sie zur Bestätigung auffordert.",
        "{0} of {1}" to "{0} von {1}",
        "%d s left" to "noch %d s",
        "Downloaded and checked (SHA-256 {0}...). Confirm the installation in the window Android shows." to "Heruntergeladen und geprüft (SHA-256 {0}...). Bestätigen Sie die Installation im Fenster, das Android anzeigt.",
        "Not installed: {0}" to "Nicht installiert: {0}",
        "That did not work" to "Das hat nicht funktioniert",
        "The downloaded file has been removed." to "Die heruntergeladene Datei wurde entfernt.",
        "PythonOS is not installed." to "PythonOS ist nicht installiert.",
        "PythonOS is installed." to "PythonOS ist installiert.",
        "The downloaded file is kept, so trying again does not download it again." to "Die heruntergeladene Datei bleibt erhalten, ein neuer Versuch lädt sie also nicht erneut herunter.",
        "No release notes." to "Keine Versionshinweise.",
        "What is new in {0}" to "Neuigkeiten in {0}",
        "Tap to open the full release page." to "Tippen, um die vollständige Versionsseite zu öffnen.",
        "Looking up versions..." to "Versionen werden gesucht...",
        "No versions found." to "Keine Versionen gefunden.",
        "Could not list versions: {0}" to "Versionen konnten nicht aufgelistet werden: {0}",
        "Install a version" to "Eine Version installieren",
        "Cancel" to "Abbrechen",
        "Install an older version?" to "Eine ältere Version installieren?",
        "You have {0}. Android refuses to install an older version over a newer one. If it does, uninstall PythonOS first (back up your files with the backup command inside PythonOS), then install again." to "Sie haben {0}. Android weigert sich, eine ältere Version über einer neueren zu installieren. Deinstallieren Sie in diesem Fall zuerst PythonOS (sichern Sie Ihre Dateien mit dem Befehl backup in PythonOS) und installieren Sie dann erneut.",
        "Try anyway" to "Trotzdem versuchen",
        "Uninstall PythonOS?" to "PythonOS deinstallieren?",
        "This removes PythonOS and everything stored inside it (accounts, files, settings) from this device. Back up first with the backup command inside PythonOS." to "Dadurch werden PythonOS und alles darin Gespeicherte (Konten, Dateien, Einstellungen) von diesem Gerät entfernt. Sichern Sie zuerst mit dem Befehl backup in PythonOS.",
        "Details copied. Paste them into a bug report." to "Details kopiert. Fügen Sie sie in einen Fehlerbericht ein.",
    )
}

/** The translated text for an English wording, with {0}, {1} ... filled in. */
fun t(english: String, vararg args: Any?): String = Lang.text(english, args)
