# pyos/locales_auto.py - machine translations of the messages nobody has translated by hand yet.
#
# GENERATED by CI (tools/translate_ci.py, .github/workflows/translations.yml) and reviewed in the pull request it opens: do not edit it.
# To correct a translation, put the right text in pyos/locales.py: a text written by a person always wins over a
# machine one, and this file then drops its own copy at the next run. A message that is missing here simply shows in English.
ES = {
}

FR = {
}

DE = {
}
