#!/usr/bin/env python3
"""Machine-translates the messages PythonOS has no translation for yet. Meant to run in CI (.github/workflows/translations.yml), which opens a
pull request with the result; nobody runs it by hand and PythonOS never runs it.

    python tools/translate_ci.py                  translate what is missing with Argos Translate and rewrite pyos/locales_auto.py
    python tools/translate_ci.py --dry-run        only say what would be translated
    python tools/translate_ci.py --summary FILE   also write the pull request text to FILE

How it works
  * the messages are every text given to tr() in the code (tools/i18n_keys.py)
  * a message that a person translated (corrections in pyos/locales.py) is never touched and always wins over a machine one
  * {placeholders}, <arguments>, file names, flags, key letters like (a) and command names such as pkg and sudo are swapped for tokens before
    translating and put back afterwards; a result that lost or changed one is thrown away
  * every result is translated back to English and compared with the original: a result that comes back as something else is thrown away
  * a message that is thrown away stays English, which is always safe: pyos/i18n.py falls back to the English text
  * the output file is written in a fixed order, so running it twice changes nothing
"""
import argparse
import difflib
import importlib.util
import json
import os
import re
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir))
sys.path.insert(0, REPO_ROOT)
sys.path.insert(0, os.path.join(REPO_ROOT, "tools"))

import i18n_keys  # noqa: E402

OUTPUT = os.path.join(REPO_ROOT, "pyos", "locales_auto.py")
LANGUAGES = {"es": "ES", "fr": "FR", "de": "DE"}                  # the languages PythonOS has (pyos/i18n.py), without English
MIN_SIMILARITY = 0.30                                              # how much of a result must survive the trip back to English
# what must come through a translation unchanged
PROTECTED = re.compile(
    r"\{\w+\}"                                                     # {placeholders}
    r"|<[^<>\s][^<>]*>"                                            # <arguments> in a command's syntax
    r"|\([a-zA-Z]\)"                                               # the key letters of a choice: (a) (N)
    r"|--[A-Za-z][\w-]*"                                           # --flags
    r"|\b(?:https?://\S+|[\w.-]*[\w-]+\.(?:json|py|log|txt|com|org|io)\b|\.OSData/[\w./-]+)"   # addresses and file names
    r"|\b(?:PythonOS|GitHub|Discord|Python|pkg|gh|sudo|doctor|updatecheck|unalias|passwd|chmod|whathappened|hwsetup|installos|DNS|Ctrl\+C|Enter)\b"
    r"|\b\d+(?:\.\d+)+\b"                                          # version numbers
)
TOKEN_FORMATS = ("⟦{n}⟧", "XQ{n}Z", "[{n}]")           # tried in this order until one survives the engine
HEADER = '''# pyos/locales_auto.py - machine translations of the messages nobody has translated by hand yet.
#
# GENERATED by CI (tools/translate_ci.py, .github/workflows/translations.yml) and reviewed in the pull request it opens: do not edit it.
# To correct a translation, put the right text in pyos/locales.py: a text written by a person always wins over a
# machine one, and this file then drops its own copy at the next run. A message that is missing here simply shows in English.
'''


class Engine:
    """Something that translates English text into a language and back. The CI uses Argos Translate; the tests use a fake one."""

    def translate(self, text, code):
        raise NotImplementedError

    def back(self, text, code):
        raise NotImplementedError


class ArgosEngine(Engine):
    def __init__(self, codes):
        import argostranslate.package
        import argostranslate.translate
        self.translate_module = argostranslate.translate
        argostranslate.package.update_package_index()
        available = argostranslate.package.get_available_packages()
        installed = {(p.from_code, p.to_code) for p in argostranslate.package.get_installed_packages()}
        for code in codes:
            for pair in (("en", code), (code, "en")):
                if pair in installed:
                    continue
                package = next((p for p in available if (p.from_code, p.to_code) == pair), None)
                if package is None:
                    raise SystemExit(f"Argos Translate has no model for {pair[0]} -> {pair[1]}")
                print(f"installing the Argos model {pair[0]} -> {pair[1]} ...", flush=True)
                argostranslate.package.install_from_path(package.download())

    def translate(self, text, code):
        return self.translate_module.translate(text, "en", code)

    def back(self, text, code):
        return self.translate_module.translate(text, code, "en")


def protect(text, token_format):
    """(text with the protected parts replaced by tokens, the parts in order)."""
    parts = []

    def swap(match):
        parts.append(match.group(0))
        return token_format.format(n=len(parts) - 1)
    return PROTECTED.sub(swap, text), parts


def restore(text, parts, token_format):
    """The original parts put back, or None when the engine lost, doubled or changed a token."""
    for n, part in enumerate(parts):
        token = token_format.format(n=n)
        if text.count(token) != 1:
            return None
        text = text.replace(token, part)
    return text


def words(text):
    return [w for w in re.findall(r"[^\W\d_]+", text.lower()) if len(w) > 1]


def similar(a, b):
    wa, wb = words(a), words(b)
    if not wa or not wb:
        return 1.0
    return difflib.SequenceMatcher(None, wa, wb).ratio()


def worth_translating(masked):
    """Text that is only tokens, or has hardly a word left, is not machine-translated (it stays English until a person does it)."""
    leftover = re.sub(r"⟦\d+⟧|XQ\d+Z|\[\d+\]", " ", masked)
    return len(words(leftover)) >= 2


def translate_one(engine, text, code):
    """(translation, None) or (None, why it was thrown away)."""
    last = "the engine changed something that must stay as it is"
    for token_format in TOKEN_FORMATS:
        masked, parts = protect(text, token_format)
        if not worth_translating(masked):
            return None, "too little to translate"
        try:
            result = engine.translate(masked, code)
        except Exception as e:                                     # noqa: BLE001 - one bad message must not stop the run
            return None, f"the engine failed ({type(e).__name__})"
        restored = restore(result, parts, token_format)
        if restored is None:
            continue
        if not restored.strip() or restored.strip() == text.strip():
            return None, "the result is empty or unchanged"
        try:
            returned = engine.back(result, code)
        except Exception as e:                                     # noqa: BLE001
            return None, f"the check failed ({type(e).__name__})"
        returned = restore(returned, parts, token_format) or returned
        score = similar(text, returned)
        if score < MIN_SIMILARITY:
            return None, f"it does not mean the same when translated back (similarity {score:.2f})"
        if set(re.findall(r"\{\w+\}", restored)) != set(re.findall(r"\{\w+\}", text)):
            return None, "its {placeholders} differ"
        return restored, None
    return None, last


def load_auto(path):
    """The current generated catalogs {code: {english: translated}} (empty when there is no file yet)."""
    if not os.path.isfile(path):
        return {code: {} for code in LANGUAGES}
    spec = importlib.util.spec_from_file_location("locales_auto_current", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return {code: dict(getattr(module, name, {})) for code, name in LANGUAGES.items()}


def load_human():
    """{code: {english: translated}} written by people (never changed by this script)."""
    from pyos import locales
    return {code: dict(locales.HUMAN[code]) for code in LANGUAGES}


def render(catalogs):
    out = [HEADER]
    for code, name in LANGUAGES.items():
        out.append(f"{name} = {{")
        for key in sorted(catalogs[code]):
            out.append(f"    {json.dumps(key, ensure_ascii=False)}: {json.dumps(catalogs[code][key], ensure_ascii=False)},")
        out.append("}")
        out.append("")
    return "\n".join(out)


def plan(keys, human, auto):
    """(what to translate per language, what to drop per language). A machine text for a message that no longer exists, or that a person has
    now translated, is dropped."""
    todo, drop = {}, {}
    for code in LANGUAGES:
        todo[code] = [k for k in keys if k not in human[code] and k not in auto[code]]
        drop[code] = [k for k in auto[code] if k not in keys or k in human[code]]
    return todo, drop


def run(engine_factory, keys, human, auto, dry_run=False):
    """The new generated catalogs and a report: {code: {"added": n, "dropped": n, "thrown_away": [(text, why)]}}."""
    todo, drop = plan(keys, human, auto)
    result = {code: dict(table) for code, table in auto.items()}
    report = {}
    engine = None
    for code in LANGUAGES:
        for key in drop[code]:
            result[code].pop(key, None)
        report[code] = {"added": 0, "dropped": len(drop[code]), "thrown_away": [], "todo": len(todo[code])}
        if dry_run or not todo[code]:
            continue
        engine = engine or engine_factory([c for c in LANGUAGES if todo[c]])
        for key in todo[code]:
            text, why = translate_one(engine, key, code)
            if text is None:
                report[code]["thrown_away"].append((key, why))
            else:
                result[code][key] = text
                report[code]["added"] += 1
    return result, report


def summary(report):
    lines = ["Machine translations made by CI. A person's translation always wins over these: correct one by adding the right text to "
             "`pyos/locales.py`. A message that could not be translated safely stays English.", ""]
    for code, info in report.items():
        lines.append(f"- **{code}**: {info['added']} added, {info['dropped']} dropped, {len(info['thrown_away'])} left in English (of {info['todo']} to do)")
    left = [(code, text, why) for code, info in report.items() for text, why in info["thrown_away"]]
    if left:
        lines += ["", "Left in English:", ""] + [f"- {code}: `{text[:70]}` - {why}" for code, text, why in left[:40]]
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--out", default=OUTPUT)
    parser.add_argument("--summary")
    args = parser.parse_args(argv)
    keys = i18n_keys.all_keys()
    human, auto = load_human(), load_auto(args.out)
    result, report = run(ArgosEngine, keys, human, auto, args.dry_run)
    text = summary(report)
    print(text)
    if args.summary:
        with open(args.summary, "w", encoding="utf-8") as f:
            f.write(text)
    if args.dry_run:
        return 0
    new = render(result)
    old = open(args.out, encoding="utf-8").read() if os.path.isfile(args.out) else ""
    if new != old:
        with open(args.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(new)
        print(f"wrote {args.out}")
    else:
        print("nothing changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
