name: Build Executables

on:
  push:
    branches:
      - main
    paths:
      - "installer/**"
      - "installer-requirements.txt"
      - ".github/workflows/build-exe.yml"
  pull_request:
    paths:
      - "installer/**"
      - "installer-requirements.txt"
      - ".github/workflows/build-exe.yml"

env:
  PUBLISH: true  # Set to false to disable publishing
  VERSION: "1.0.0"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r installer-requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --name app_windows.exe installer/run.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/app_windows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r installer-requirements.txt
          pip install pyinstaller

      - name: Build Linux Executable (AppImage)
        run: |
          pyinstaller --onefile --name app_linux installer/run.py
          mv dist/app_linux dist/app_linux.AppImage

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/app_linux.AppImage

  publish:
    needs: [build-windows, build-linux]
    if: env.PUBLISH == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Executable
        uses: actions/download-artifact@v4
        with:
          name: windows-exe
          path: release/

      - name: Download Linux Executable
        uses: actions/download-artifact@v4
        with:
          name: linux-app
          path: release/

      - name: Add Source Code (run.py)
        run: cp installer/run.py release/

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          files: |
            release/app_windows.exe
            release/app_linux.AppImage
            release/run.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
