name: Build Executables

on:
  push:
    branches:
      - main
    paths:
      - "installer/**"
      - "buildozer.spec"
      - "installer-requirements.txt"
      - ".github/workflows/build-exe.yml"
  pull_request:
    paths:
      - "installer/**"
      - "buildozer.spec"
      - "installer-requirements.txt"
      - ".github/workflows/build-exe.yml"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r installer-requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --name "myapp_${{ env.VERSION }}_windows.exe" installer/run.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/myapp_*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r installer-requirements.txt
          pip install pyinstaller

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile --name "myapp_${{ env.VERSION }}_linux.AppImage" installer/run.py

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/myapp_*.AppImage
          
  upload-runpy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Verify run.py exists
        run: |
          if [ ! -f "installer/run.py" ]; then
            echo "Error: installer/run.py not found!"
            exit 1
          fi
  
      - name: Upload run.py
        uses: actions/upload-artifact@v4
        with:
          name: installer-runpy
          path: installer/run.py
  