name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r installer-requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile --name app_windows.exe installer/run.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/app_windows.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r installer-requirements.txt
          pip install pyinstaller

      - name: Build Linux Executable
        run: |
          pyinstaller --onefile --name app_linux installer/run.py

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/app_linux

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk
          pip install buildozer cython virtualenv

      - name: Initialize Buildozer
        run: |
          sed -i 's|source.include_exts = .*|source.include_exts = py|' buildozer.spec
          sed -i 's|source.include_patterns = .*|source.include_patterns = installer/*|' buildozer.spec
          sed -i 's|source.main = main.py|source.main = installer/run.py|' buildozer.spec
          sed -i 's|requirements = python3|requirements = python3,'"$(tr '\n' ',' < installer-requirements.txt)"'|' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
